In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter

In [2]:
# Parameters
seq_len = 10  # window size for input sequences
data_columns = ['d1', 'd2', 'd3', 'd4', 'd5', 'd6', 'bonus']

num_epochs = 100    # Epoch 100/100, Loss: 8.0247

# learning_rate = 0.01   # Epoch 10/10, Loss: 19.3940
learning_rate = 0.001    # original Epoch 10/10, Loss: 18.2901
# batch size hyperparameter
batch_size = 32
# key hyperparameter that controls the size of the embedding vectors for categorical values
embedding_dim = 128

In [3]:
# Read and preprocess data
file_path = '../data/data_all_l649.xlsx'
df = pd.read_excel(file_path)
df = df.reset_index(drop=True)
df = df.drop(columns=['date'])
input_data = df[data_columns].values.astype(int)
print(f"input data shape: {input_data.shape}")
print(f"input data type: {input_data.dtype}")
print(input_data[:5])  # Display first 5 rows of labels
print('...')
print(input_data[-5:])  # Display last 5 rows of labels
print("Data loaded and preprocessed successfully.")

input data shape: (4353, 7)
input data type: int64
[[ 3 11 12 14 41 43 13]
 [ 8 33 36 37 39 41  9]
 [ 1  6 23 24 27 39 34]
 [ 3  9 10 13 20 43 34]
 [ 5 14 21 31 34 47 45]]
...
[[ 9 10 12 17 46 49 30]
 [ 1  7 15 19 36 40 47]
 [26 27 30 38 47 48 43]
 [24 31 37 41 45 46 16]
 [17 22 24 40 42 46 29]]
Data loaded and preprocessed successfully.


In [4]:
# Check if CUDA is available and set device accordingly
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [5]:
# Create input/output sequences based on seq_len size of the window.
# for each target create a sequence of seq_len preceeding inputs
inputs = []
targets = []
for i in range(len(input_data) - seq_len):
    seq = input_data[i:i+seq_len]           # shape: [seq_len, 7]
    tgt = input_data[i+seq_len]             # shape: [7]
    inputs.append(seq)
    targets.append(tgt)

inputs = np.array(inputs)    # shape: [num_samples, seq_len, 7]
targets = np.array(targets)  # shape: [num_samples, 7]
inputs = torch.tensor(inputs, dtype=torch.long).to(device)
targets = torch.tensor(targets, dtype=torch.long).to(device)
print(f"inputs: {inputs.shape}, targets shape: {targets.shape}")
print(inputs[0])  # Display first input sequence
print(targets[0])  # Display first target sequence

inputs: torch.Size([4343, 10, 7]), targets shape: torch.Size([4343, 7])
tensor([[ 3, 11, 12, 14, 41, 43, 13],
        [ 8, 33, 36, 37, 39, 41,  9],
        [ 1,  6, 23, 24, 27, 39, 34],
        [ 3,  9, 10, 13, 20, 43, 34],
        [ 5, 14, 21, 31, 34, 47, 45],
        [ 8, 20, 21, 25, 31, 41, 33],
        [18, 25, 28, 33, 36, 42,  7],
        [ 7, 16, 17, 31, 40, 48, 26],
        [ 5, 10, 23, 27, 37, 38, 33],
        [ 4, 15, 30, 37, 46, 48,  3]], device='cuda:0')
tensor([ 7,  9, 21, 33, 38, 42, 45], device='cuda:0')


In [6]:
class SequenceDataset(Dataset):
    """
    PyTorch Dataset for sequence modeling.
    Each item is a tuple (X, y) where:
      - X: input tensor of shape [seq_len, 7] (sequence of events)
      - y: target tensor of shape [7] (next event to predict)
    Used for batching input/output pairs for transformer models.
    """
    def __init__(self, X, y):
        self.X = X
        self.y = y
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [7]:
# Create a dataset that has corresponding inputs and targets
dataset = SequenceDataset(inputs, targets)
# Create a dataloader for a defined batch size, shuffle is False because order is important
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
print(f"Dataset length: {len(dataset)}")
print(f"First sample: {dataset[0]}")
print(f"Last sample: {dataset[-1]}")

Dataset length: 4343
First sample: (tensor([[ 3, 11, 12, 14, 41, 43, 13],
        [ 8, 33, 36, 37, 39, 41,  9],
        [ 1,  6, 23, 24, 27, 39, 34],
        [ 3,  9, 10, 13, 20, 43, 34],
        [ 5, 14, 21, 31, 34, 47, 45],
        [ 8, 20, 21, 25, 31, 41, 33],
        [18, 25, 28, 33, 36, 42,  7],
        [ 7, 16, 17, 31, 40, 48, 26],
        [ 5, 10, 23, 27, 37, 38, 33],
        [ 4, 15, 30, 37, 46, 48,  3]], device='cuda:0'), tensor([ 7,  9, 21, 33, 38, 42, 45], device='cuda:0'))
Last sample: (tensor([[14, 22, 24, 28, 34, 35,  4],
        [12, 25, 26, 38, 39, 41, 16],
        [11, 25, 30, 35, 46, 49, 37],
        [13, 21, 23, 33, 35, 45,  1],
        [ 3, 12, 23, 27, 33, 45, 22],
        [ 7,  9, 19, 34, 39, 44, 38],
        [ 9, 10, 12, 17, 46, 49, 30],
        [ 1,  7, 15, 19, 36, 40, 47],
        [26, 27, 30, 38, 47, 48, 43],
        [24, 31, 37, 41, 45, 46, 16]], device='cuda:0'), tensor([17, 22, 24, 40, 42, 46, 29], device='cuda:0'))


In [8]:
# Define the SimpleLSTM model class
class SimpleLSTM(nn.Module):
    def __init__(self, vocab_size=50, embed_dim=embedding_dim, hidden_dim=128, num_layers=1, num_outputs=6):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.lstm = nn.LSTM(input_size=embed_dim, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        self.fc = nn.ModuleList([nn.Linear(hidden_dim, vocab_size) for _ in range(num_outputs)])
        self.num_outputs = num_outputs
    def forward(self, x):
        # x shape: [batch_size, seq_len, 7]
        batch_size, seq_len, num_features = x.shape
        # Embed each categorical value
        x = self.embedding(x)  # [batch_size, seq_len, 7, embed_dim]
        # Aggregate features for each event (mean or sum)
        x = x.mean(dim=2)      # [batch_size, seq_len, embed_dim]
        lstm_out, _ = self.lstm(x)
        x = lstm_out[:, -1, :]  # use last time step's output
        outs = [fc(x) for fc in self.fc]  # list of [batch_size, vocab_size]
        return outs


In [9]:
# Instantiate the LSTM model for training
model = SimpleLSTM(num_outputs=6)  # 6 unique values
model = model.to(device)  # Move model to CUDA if available

# TensorBoard writer uses default directory ./runs
# to view results run tensorboard --logdir runs
writer = SummaryWriter()

# Training loop for the LSTM model
# Use CrossEntropyLoss for each output
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    model.train()
    total_loss = 0
    for batch_X, batch_y in dataloader:
        batch_X = batch_X.to(device)
        batch_y = batch_y.to(device)
        optimizer.zero_grad()
        outs = model(batch_X)  # list of 6 outputs, each [batch_size, vocab_size]
        # For each output, compute loss against the corresponding target value
        loss = 0
        for i in range(6):
            loss += criterion(outs[i], batch_y[:, i])
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss = total_loss / len(dataloader)
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")
    writer.add_scalar('Loss/train', avg_loss, epoch)

# Log hyperparameters and final loss to TensorBoard
hparams = {
    'seq_len': seq_len,
    'num_epochs': num_epochs,
    'batch_size': batch_size,
    'embedding_dim': embedding_dim,
    'learning_rate': learning_rate,
}
metrics = {
    'final_loss': avg_loss
}
writer.add_hparams(hparams, metrics)

print("Training complete.")
writer.close()


Epoch 1/100, Loss: 20.0738
Epoch 2/100, Loss: 19.5165
Epoch 2/100, Loss: 19.5165
Epoch 3/100, Loss: 19.4569
Epoch 3/100, Loss: 19.4569
Epoch 4/100, Loss: 19.3918
Epoch 4/100, Loss: 19.3918
Epoch 5/100, Loss: 19.3048
Epoch 5/100, Loss: 19.3048
Epoch 6/100, Loss: 19.2109
Epoch 6/100, Loss: 19.2109
Epoch 7/100, Loss: 19.1089
Epoch 7/100, Loss: 19.1089
Epoch 8/100, Loss: 18.9966
Epoch 8/100, Loss: 18.9966
Epoch 9/100, Loss: 18.8747
Epoch 9/100, Loss: 18.8747
Epoch 10/100, Loss: 18.7459
Epoch 10/100, Loss: 18.7459
Epoch 11/100, Loss: 18.6079
Epoch 11/100, Loss: 18.6079
Epoch 12/100, Loss: 18.4566
Epoch 12/100, Loss: 18.4566
Epoch 13/100, Loss: 18.2929
Epoch 13/100, Loss: 18.2929
Epoch 14/100, Loss: 18.1226
Epoch 14/100, Loss: 18.1226
Epoch 15/100, Loss: 17.9310
Epoch 15/100, Loss: 17.9310
Epoch 16/100, Loss: 17.7260
Epoch 16/100, Loss: 17.7260
Epoch 17/100, Loss: 17.5301
Epoch 17/100, Loss: 17.5301
Epoch 18/100, Loss: 17.3446
Epoch 18/100, Loss: 17.3446
Epoch 19/100, Loss: 17.1432
Epoch 19/

In [10]:
# Prep last sequence of input data for inference
last_seq = torch.tensor(input_data[-seq_len:], dtype=torch.long).unsqueeze(0).to(device)  # shape: [1, seq_len, 7]

print(last_seq)

tensor([[[12, 25, 26, 38, 39, 41, 16],
         [11, 25, 30, 35, 46, 49, 37],
         [13, 21, 23, 33, 35, 45,  1],
         [ 3, 12, 23, 27, 33, 45, 22],
         [ 7,  9, 19, 34, 39, 44, 38],
         [ 9, 10, 12, 17, 46, 49, 30],
         [ 1,  7, 15, 19, 36, 40, 47],
         [26, 27, 30, 38, 47, 48, 43],
         [24, 31, 37, 41, 45, 46, 16],
         [17, 22, 24, 40, 42, 46, 29]]], device='cuda:0')


In [11]:
# Inference for the next event using the last seq_len inputs
# Take the last sequence from the input data
# last_seq = inputs[-1].unsqueeze(0).to(device)  # shape: [1, seq_len, 7], move to CUDA if available

with torch.no_grad():
    # Pass the last sequence to the model
    outs = model(last_seq)  # list of 6 outputs, each [1, vocab_size]
    # print("Raw model outputs (logits) for each predicted value:")
    # for i, out in enumerate(outs):
    #     print(f"Output {i+1}:", out[0].cpu().numpy())
    pred_vals = []
    for out in outs:
        # For each output, get the predicted category
        val = torch.argmax(out[0])
        pred_vals.append(val.item())
    # Ensure uniqueness among the 6 predicted values
    unique_pred = []
    for val in pred_vals:
        if val not in unique_pred and len(unique_pred) < 6:
            unique_pred.append(val)
    # If not enough unique, fill with remaining unused values
    if len(unique_pred) < 6:
        unused = set(range(50)) - set(unique_pred)
        unique_pred += list(unused)[:6-len(unique_pred)]
    print(f"Predicted 6 unique values for the next event: {unique_pred}")


Predicted 6 unique values for the next event: [5, 7, 35, 46, 43, 0]


In [12]:
# Save the trained LSTM model and all necessary info for later loading and inference
import os
save_dir = './saved_model'
os.makedirs(save_dir, exist_ok=True)
model_path = os.path.join(save_dir, 'simplelstm_model.pth')
info_path = os.path.join(save_dir, 'simplelstm_model_info.pth')

# Save model state dict
torch.save(model.state_dict(), model_path)

# Save hyperparameters and other info needed for loading
model_info = {
    'vocab_size': 50,
    'embed_dim': embedding_dim,
    'hidden_dim': 128,
    'num_layers': 1,
    'num_outputs': 6,
    'seq_len': seq_len,
    'data_columns': data_columns,
}
torch.save(model_info, info_path)

print(f"LSTM model and info saved to {save_dir}")

# Save the SimpleLSTM class definition to a Python file for reuse
class_code = '''import torch.nn as nn\n\nclass SimpleLSTM(nn.Module):\n    def __init__(self, vocab_size=50, embed_dim=64, hidden_dim=128, num_layers=1, num_outputs=6):\n        super().__init__()\n        self.embedding = nn.Embedding(vocab_size, embed_dim)\n        self.lstm = nn.LSTM(input_size=embed_dim, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)\n        self.fc = nn.ModuleList([nn.Linear(hidden_dim, vocab_size) for _ in range(num_outputs)])\n        self.num_outputs = num_outputs\n    def forward(self, x):\n        batch_size, seq_len, num_features = x.shape\n        x = self.embedding(x)  # [batch_size, seq_len, 7, embed_dim]\n        x = x.mean(dim=2)      # [batch_size, seq_len, embed_dim]\n        lstm_out, _ = self.lstm(x)\n        x = lstm_out[:, -1, :]  # use last time step's output\n        outs = [fc(x) for fc in self.fc]  # list of [batch_size, vocab_size]\n        return outs\n'''
class_path = os.path.join(save_dir, 'simplelstm_class.py')
with open(class_path, 'w') as f:
    f.write(class_code)
print(f'SimpleLSTM class definition saved to {class_path}')

LSTM model and info saved to ./saved_model
SimpleLSTM class definition saved to ./saved_model\simplelstm_class.py
